spring.application.name=IISFinal

spring.datasource.url=jdbc:h2:file:./data/iisfinal;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yamlzdGhhdG11c3RiZWF0bGVhc3Q2NGNoYXJz
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000

app.use-stripe-api=true
app.stripe.api-key=sk_test_51TddHHBS9BiNpNJSzsqZwhjVcF7tM16lWjaHpgjYdAEJDVm35bGQ6lCygNfUpuddqQ6B4fSpfwgorIMzXf7HnAIp00DkJnTwBW

app.xml-output-path=./data/coupons.xml

cxf.path=/soap

grpc.server.port=9090

spring.graphql.graphiql.enabled=true

logging.level.hr.algebra=DEBUG
logging.level.org.apache.cxf=WARN