spring.application.name=IISFinal

# H2 Database (file-based, survives restarts)
spring.datasource.url=jdbc:h2:file:./data/iisfinal;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
app.jwt.secret=dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yamlzdGhhdG11c3RiZWF0bGVhc3Q2NGNoYXJz
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000

# Config switch: false = use local DB, true = use Stripe API
app.use-stripe-api=false
app.stripe.api-key=sk_test_51TddHHBS9BiNpNJSzsqZwhjVcF7tM16lWjaHpgjYdAEJDVm35bGQ6lCygNfUpuddqQ6B4fSpfwgorIMzXf7HnAIp00DkJnTwBW

# XML output path for generated coupons.xml
app.xml-output-path=./data/coupons.xml

# SOAP
cxf.path=/soap

# gRPC server port
grpc.server.port=9090

# GraphQL
spring.graphql.graphiql.enabled=true

# Logging
logging.level.hr.algebra=DEBUG
logging.level.org.apache.cxf=WARN